import * as React from "react"
import {
  Activity,
  AlertCircle,
  AlertTriangle,
  ArrowDown,
  ArrowRight,
  ArrowUp,
  AtSign,
  Bell,
  Bold,
  Calendar,
  Clock,
  Check,
  CheckCircle2,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  Code,
  Command,
  CreditCard,
  Edit,
  File,
  FileText,
  Filter,
  Folder,
  Hash,
  Image,
  Info,
  Italic,
  Laptop,
  LayoutDashboard,
  Link,
  Loader2,
  Lock,
  LogOut,
  MessageSquare,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Paperclip,
  Pencil,
  Pin,
  Plus,
  Reply,
  Search,
  Send,
  Settings,
  Smile,
  SunMedium,
  Trash,
  User,
  X,
  Inbox,
  Users,
  Star,
  Sparkles,
  Globe,
  Eye,
  EyeOff,
  Phone,
  Video,
  ExternalLink,
  QrCode,
  Copy,
  HardDrive,
  UploadCloud,
  FolderPlus,
  Upload,
  Download,
  ArrowLeft,
  Grid,
  List,
  Mic,
  Share,
  LayoutTemplate,
  DownloadCloud,
  SortDesc,
  PieChart,
  CheckCircle,
  Archive,
  UserPlus,
  ArrowUpCircle,
  Minus,
  ArrowDownCircle,
  Kanban,
  GitCommit,
  Shield,
  Music,
  Target,
  PlayCircle,
  TrendingUp,
  Zap,
  type LucideIcon,
} from "lucide-react"

export type Icon = LucideIcon

export const Icons = {
  logo: Command,
  dashboard: LayoutDashboard,
  settings: Settings,
  profile: User,
  user: User,
  calendar: Calendar,
  projects: Folder,
  folder: Folder,
  tasks: CheckCircle2,
  bell: Bell,
  search: Search,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  logout: LogOut,
  plus: Plus,
  close: X,
  check: Check,
  spinner: Loader2,
  activity: Activity,
  clock: Clock,
  pencil: Pencil,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  chevronDown: ChevronDown,
  moreHorizontal: MoreHorizontal,
  moreVertical: MoreVertical,
  trash: Trash,
  warning: AlertTriangle,
  error: AlertCircle,
  alertCircle: AlertCircle,
  info: Info,
  success: CheckCircle2,
  file: File,
  fileText: FileText,
  image: Image,
  circle: Circle,
  arrowRight: ArrowRight,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  billing: CreditCard,
  inbox: Inbox,
  users: Users,
  star: Star,
  sparkles: Sparkles,
  globe: Globe,
  lock: Lock,
  google: Globe,
  eye: Eye,
  eyeOff: EyeOff,
  // Chat icons
  hash: Hash,
  send: Send,
  reply: Reply,
  pin: Pin,
  edit: Edit,
  bold: Bold,
  italic: Italic,
  code: Code,
  link: Link,
  atSign: AtSign,
  smile: Smile,
  paperclip: Paperclip,
  messageSquare: MessageSquare,
  filter: Filter,
  checkSquare: CheckSquare,
  phone: Phone,
  video: Video,
  externalLink: ExternalLink,
  qrCode: QrCode,
  copy: Copy,
  x: X,
  hardDrive: HardDrive,
  uploadCloud: UploadCloud,
  folderPlus: FolderPlus,
  upload: Upload,
  download: Download,
  arrowLeft: ArrowLeft,
  grid: Grid,
  list: List,
  mic: Mic,
  share: Share,
  layoutTemplate: LayoutTemplate,
  downloadCloud: DownloadCloud,
  sortDesc: SortDesc,
  pieChart: PieChart,
  checkCircle: CheckCircle,
  archive: Archive,
  userPlus: UserPlus,
  arrowUpCircle: ArrowUpCircle,
  minus: Minus,
  arrowDownCircle: ArrowDownCircle,
  kanban: Kanban,
  gitCommit: GitCommit,
  loader2: Loader2,
  shield: Shield,
  music: Music,
  target: Target,
  playCircle: PlayCircle,
  trendingUp: TrendingUp,
  zap: Zap,
}

